## Oefeningen Python - Numpy

Hieronder vind je je eerste oefening voor het vak data science.
Voor je aan de oefening begint geef ik je nog de volgende handige shortcuts mee om sneller te kunnen werken met een jupyter notebook

* Uitvoeren van een cel:
    * Jupyter Notebook: Shift+Enter
    * Meeste editors: Ctrl+Enter (of Cmd+Enter op Mac)
* Nieuwe cel toevoegen:
    * Boven: A
    * Onder: B
* Cel verwijderen: D, D (twee keer op D drukken)
* Cel type veranderen: Y (code), M (markdown)

Daarnaast heeft Jupyter Notebook speciale commando's die beginnen met een procentteken (%) of met uitroepingsteken. Het uitroepingsteken kan gebruikt worden om rechtstreeks commando's op de command line interface uit te voeren. Dit gebruiken we bijvoorbeeld om packages te installeren. Een voorbeeld hiervan staat hieronder om het numpy-package te installeren dat je gaat gebruiken in deze oefening. 
De commando's met een procentteken kunnen bijvoorbeeld gebruikt worden om de looptijd van een commando te bepalen of de inhoud van een cel te bewaren in een file.

De oefening in deze notebook maakt gebruik van de numpy package en verondersteld dat je reeds de kaggle-tutorial over python gevolgd hebt.
Indien het numpy-package nog niet geinstalleerd zou zijn (dan krijg je een error met boodschap "module not found") kan je het installeren met volgende commando:

In [ ]:
!pip install numpy

Na installatie van de package kan je aan onderstaande oefeningen beginnen.
Aangezien deze oefeningen bedoeld zijn om de basissyntax van python in te oefenen raad ik het gebruik van AI-tools af. Echter kan je het wel steeds gebruiken als inspiratie, debugging, controleren of alternatieve coderingstechnieken te bekijken.


## Gok het correcte getal

Maak een klasse voor een spel waarbij je een willekeurig getal moet gokken.
Deze klasse moet de volgende zaken doen:
* Een willekeurig getal tussen 0 en 20 genereren
* Een "start" functie hebben om het spel te starten
* In deze functie moet er herhaaldelijk om input gevraagd worden aan de gebruiker.
* De input moet vergeleken worden met het random getal. Als je input:
    * kleiner is dan het willekeurig getal, print je "Te laag"
    * groter is dan het willekeurig getal, print je "Te hoog"
    * gelijk is aan het getal, eindig je en print je dat je bent gewonnen
    * Gelijk is aan "Exit", eindig je en print je dat je verloren bent.
* Om te eindigen print je nog de volgende statistieken:
    * Hoeveel keer dat je gegokt hebt
    * Hoeveel je er gemiddeld naast zat
    
Vergeet zeker niet om de code te voorzien om het spel te starten

In [3]:
np.random.randint(0,20)

7

In [4]:
import numpy as np
class Game:

    def __init__(self):

        self.target = np.random.randint(0,20)


    def start(self):

        done = False
        guesses = 0
        error = 0
    
        while not done:
            guess = input("Geef een gok in")

            if guess == "Exit":
                print("Verloren")
                break

            guess = int(guess)
            guesses += 1
            error += abs(guess-self.target)

            if guess < self.target:
                print(" Te laag")
            elif guess > self.target:
                print(" Te hoog")
            else:
                print(f"Gewonnen na {guesses} gokken en gemiddelde fout van {error/guesses}")
                break

game = Game()
game.start()


 Te hoog
 Te laag
 Te laag
 Te laag
Gewonnen na 5 gokken en gemiddelde fout van 1.6


## Matrix bewerkingen

Maak functie voor het aanmaken een matrix waar elk waarde het product is van zijn rij en kolom index (bvb op rij 4 en kolom 5 moet er 20 staan). Deze functie moet als argument het aantal rij en aantal kolommen hebben.

Maak met behulp van deze functie een matrix "a" van 5 rijen en 7 kolommen aan.

In [15]:
def init_matrix(rows, columns):
    tmp = np.zeros((rows, columns))

    for i in range(rows):
        for j in range(columns):
            tmp[i,j] = i*j
    
    return tmp

a = init_matrix(5, 7)
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12.],
       [ 0.,  3.,  6.,  9., 12., 15., 18.],
       [ 0.,  4.,  8., 12., 16., 20., 24.]])

Maak een functie die met behulp van slicing de volgorde van de elementen in matrix "a" omdraait.

In [10]:
a[-1::-1, -1::-1]

array([[0.44410007, 0.71008976, 0.47324725, 0.34848112, 0.19313005,
        0.44855723, 0.1920278 ],
       [0.50504778, 0.4275772 , 0.5469523 , 0.74327418, 0.81388247,
        0.92748965, 0.53982758],
       [0.92314271, 0.52398845, 0.76742121, 0.09808677, 0.42791815,
        0.32987031, 0.79646355],
       [0.72426971, 0.69610095, 0.49041134, 0.82754131, 0.79516238,
        0.55327057, 0.67337585],
       [0.83738639, 0.10901377, 0.73434897, 0.66158959, 0.15150634,
        0.72933959, 0.03670303]])

Bereken de mean, median en standard deviation van elke kolom in matrix  "a".

In [11]:
np.mean(a, axis=1)

array([0.46569824, 0.68001887, 0.55241302, 0.64343588, 0.40137618])

Bereken hoeveel elementen in matrix "a" groter zijn dan 20

In [12]:
np.sum(a>20)

np.int64(0)

In [1]:
%pip list

Package                   Version
------------------------- -----------------
absl-py                   2.1.0
annotated-types           0.7.0
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
astunparse                1.6.3
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bleach                    6.1.0
blinker                   1.8.2
certifi                   2024.7.4
cffi                      1.17.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.2.1
cycler                    0.12.1
dacite                    1.8.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
dnspython                 2.6.1
et-xmlfile                1.1.0
executing       